// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Performer } from "./Performer";
import type { Piece } from "./Piece";

export type Concert = { datetime: string, url: string, performers: Array<Performer>, title: string, subtitle: string | null, description: string | null, is_wigmore_u35: boolean, programme_pdf_url: string | null, pieces: Array<Piece>, venue: string, };