name: "Deploy website"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [edited]
  # schedule:
  #   - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10


      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust -> target"

      # Web scraping doesn't work on GitHub Actions due to
      # Cloudflare.
      #
      # - name: Generate JSON containing all concerts
      #   run: pnpm rust
      #   env:
      #     RUST_LOG: "london_classical"

      - name: Download JSON data from release
        run: |
          mkdir -p src/assets
          cd src/assets
          curl -LO https://github.com/penelopeysm/london_classical/releases/download/json/concerts.json

      - name: Generate TypeScript types from Rust structs
        run: pnpm rust:types

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm build --base /london_classical

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          keep_files: false
          user_name: "GitHub Actions"
          user_email: "github-actions[bot]@users.noreply.github.com"
